# Generated by Django 4.2.3 on 2023-07-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quize', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quize',
            name='test_status',
            field=models.CharField(default='pending', max_length=200),
        ),
    ]
