# Generated by Django 4.2.3 on 2023-07-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quize', '0002_quize_test_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='quize',
            name='user_role',
            field=models.CharField(default='user', max_length=200),
        ),
    ]
